# Generated by Django 5.2.3 on 2025-08-21 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_remove_order_total_price_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('network', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=10)),
                ('amount_crypto', models.DecimalField(decimal_places=18, max_digits=36)),
                ('receiving_address', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
