- name: Clean ALL & Deploy Nginx (no sudo, sin heredoc)
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_SSH_KEY }}
    port: ${{ secrets.VPS_PORT || 22 }}
    script_stop: true
    script: |
      set -e

      # matar todo
      docker ps -aq | xargs -r docker rm -f
      docker network prune -f || true

      # base dir escribible
      pick_writable_dir() {
        for d in "$HOME" "$(pwd)" /var/tmp /tmp; do
          if [ -n "$d" ] && mkdir -p "$d/.probe" >/dev/null 2>&1; then
            rmdir "$d/.probe" 2>/dev/null || true
            echo "$d"
            return 0
          fi
        done
        echo "/tmp"
      }
      BASE_DIR="$(pick_writable_dir)"
      APP_DIR="${BASE_DIR%/}/nginx-test"
      SITE_DIR="${APP_DIR}/site"
      mkdir -p "${SITE_DIR}"

      # escribir HTML con un único comando
      printf '%s' '<!doctype html>
<html lang="es"><head><meta charset="utf-8"><title>OK - Nginx CI</title></head>
<body style="font-family:system-ui;margin:40px;">
  <h1>✅ Deploy Nginx limpio (sin heredoc)</h1>
  <p>Servido por <strong>nginx:alpine</strong> lanzado desde <strong>GitHub Actions</strong>.</p>
  <p>Hora del servidor: <span id="ts"></span></p>
  <script>document.getElementById("ts").textContent = new Date().toString();</script>
</body></html>' > "${SITE_DIR}/index.html"

      docker pull nginx:alpine
      docker run -d --name nginx-test \
        --restart unless-stopped \
        -p 8080:80 \
        -v "${SITE_DIR}:/usr/share/nginx/html:ro" \
        nginx:alpine
