name: SSH Test
on: workflow_dispatch

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            hostname
            whoami
            uname -a
            docker --version
