name: Django CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: productmanagement_db
          POSTGRES_USER: productmanagement_db_user
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DEBUG: 'False'
      USE_POSTGRES: 'True'
      # Variables para el CONTENEDOR LOCAL (no Render)
      POSTGRES_DB: productmanagement_db
      POSTGRES_USER: productmanagement_db_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: '5432'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: 'localhost,127.0.0.1'
      DJANGO_SETTINGS_MODULE: 'config.settings'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U productmanagement_db_user; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
          sleep 5

      - name: Test PostgreSQL connection
        run: |
          echo "Testing direct PostgreSQL connection..."
          PGPASSWORD=postgres psql -h localhost -p 5432 -U productmanagement_db_user -d productmanagement_db -c "SELECT version();" || echo "Direct PostgreSQL connection failed"

      - name: Verify Django database connection
        run: |
          echo "Testing Django database connection..."
          python -c "
          import os
          import django
          from django.conf import settings
          os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
          django.setup()
          from django.db import connection
          try:
              cursor = connection.cursor()
              cursor.execute('SELECT version();')
              version = cursor.fetchone()
              print(f'✅ Database connection successful: {version[0]}')
          except Exception as e:
              print(f'❌ Database connection failed: {e}')
              exit(1)
          " || echo "Django database connection failed"

      - name: Create and run migrations
        run: |
          echo "Making migrations..."
          python manage.py makemigrations --verbosity=2
          echo "Running migrations..."
          python manage.py migrate --verbosity=2
          echo "Showing migration status..."
          python manage.py showmigrations

      - name: Verify tables were created
        run: |
          echo "Checking created tables..."
          PGPASSWORD=postgres psql -h localhost -p 5432 -U productmanagement_db_user -d productmanagement_db -c "\dt" || echo "Could not list tables"

      - name: Load initial data (fixtures)
        run: |
          echo "Loading fixtures..."
          if [ -f "fixtures/inicial.json" ]; then
            python manage.py loaddata fixtures/inicial.json --verbosity=2
          else
            echo "No fixture file found at fixtures/inicial.json - skipping"
          fi
        continue-on-error: true

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput --verbosity=2

      - name: Run Django tests
        run: |
          echo "Running tests..."
          python manage.py test --verbosity=2 --keepdb
          echo "Tests completed!"

      - name: Final database verification
        run: |
          echo "Final verification - listing all tables..."
          PGPASSWORD=postgres psql -h localhost -p 5432 -U productmanagement_db_user -d productmanagement_db -c "
            SELECT schemaname, tablename 
            FROM pg_tables 
            WHERE schemaname = 'public' 
            ORDER BY tablename;
          " || echo "Could not verify final database state"