name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DEBUG: 'False'
      USE_POSTGRES: 'True'
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: '5432'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load initial data (fixtures)
        run: |
          python manage.py loaddata fixtures/inicial.json

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          python manage.py test

      - name: Apply database migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
