# Generated by Django 5.2.3 on 2025-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='defaults/no-image-available.png', null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
